### ISSUE TITLE
DOM Clobbering Browser Compatibility

### ISSUE THREAD

**Issue by FlandreDaisuki** [aszx87410/beyond-xss#2]
> 如果要回傳的東西有多個，就回傳 HTMLCollection。

```html
<!DOCTYPE html>
<html>
<body>
  <a id="config"></a>
  <a id="config"></a>
  <script>
    console.log(config) // HTMLCollection(2)
  </script>
</body>
</html>
```

Firefox 會回傳第一個 `[id="config"]` 的元素，要做到一樣的行為還是要用 `<form name="config">`，因此下面利用 `HTMLCollection` 特性的範例在 Firefox 都不會生效。

splitline 的 [DOM-Clobber3r](https://splitline.github.io/DOM-Clobber3r/) 不是用這個特性所以比較通用。

- - -

Environment: Firefox 119.0b4

**Comment by aszx87410** [comment]
感謝回報，這是已知問題但之前沒有一併寫到，已經修正相關文章段落，多加了一些附註：https://github.com/aszx87410/beyond-xss/commit/4d51896b29e7882c9eb0614e8f7c02953d849031
